name: build.yml
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  build_maps:
    runs-on: ubuntu-latest
    steps:
      # - copy code below to release.yml -
      - uses: actions/checkout@v4
      - name: Install base dependencies
        run: |
          sudo apt update
          sudo apt -y install smpq parallel
      - name: Build
        run: |
          ./build_release_package.sh
      - name: Push Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: Archipelago-SC2Data

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: target
          retention-days: 7
